name: Python Test Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run_python_tests:
    name: Run Duck Compiler Tests (Python)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rust Toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Run Python Test Script in CI/CD Mode
      run: |
        ./install_std.sh
        cd ./tests
        export RUST_BACKTRACE=0
        python run_tests.py --cicd --release
